export const LANGUAGES = [
  {
    name: "ActionScript",
    releaseYear: 1998,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "AngleScript",
    releaseYear: 2003,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Bash",
    releaseYear: 1989,
    compiled: false,
    objectOriented: false,
  },
  {
    name: "BASIC",
    releaseYear: 1964,
    compiled: false,
    objectOriented: true,
  },
  {
    name: "C++",
    releaseYear: 1985,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "C#",
    releaseYear: 2000,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "C",
    releaseYear: 1972,
    compiled: true,
    objectOriented: false,
  },
  {
    name: "Carbon",
    releaseYear: "No data",
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Clojure",
    releaseYear: 2007,
    compiled: true,
    objectOriented: false,
  },
  {
    name: "Dart",
    releaseYear: 2011,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Elixir",
    releaseYear: 2012,
    compiled: true,
    objectOriented: false,
  },
  {
    name: "Erlang",
    releaseYear: 1986,
    compiled: true,
    objectOriented: false,
  },
  {
    name: "F#",
    releaseYear: 2005,
    compiled: false,
    objectOriented: false,
  },
  {
    name: "Fortran",
    releaseYear: 1957,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Go",
    releaseYear: 2009,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Java",
    releaseYear: 1995,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "JavaScript",
    releaseYear: 1995,
    compiled: false,
    objectOriented: true,
  },
  {
    name: "Julia",
    releaseYear: 2012,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Kotlin",
    releaseYear: 2011,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Lisp",
    releaseYear: 1960,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Lua",
    releaseYear: 1993,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Objective-C",
    releaseYear: 1984,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "PHP",
    releaseYear: 1995,
    compiled: false,
    objectOriented: true,
  },
  {
    name: "Python",
    releaseYear: 1991,
    compiled: false,
    objectOriented: true,
  },
  {
    name: "Ruby",
    releaseYear: 1995,
    compiled: false,
    objectOriented: true,
  },
  {
    name: "Rust",
    releaseYear: 2015,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "Swift",
    releaseYear: 2014,
    compiled: true,
    objectOriented: true,
  },
  {
    name: "TypeScript",
    releaseYear: 2012,
    compiled: true,
    objectOriented: true,
  },
];
